[package]
name = "svg-animate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
nom-derive = "0.10.1"
svg = "0.13.1"
derive-parse = {path = "derive"}
pest = "2.7.2"
pest_derive = "2.7.2"
derive_more = "0.99.17"
nom_locate = "4.1.0"
